theme: minima
title: Mincheo@DevForBeginners
author: Mincheol
email: the7mincheol@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm doing the assignment of DevForBeginners.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
